### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by jonas-spls** [yl-1993/learn-to-cluster#100]
Hi, I have a list of unlabeled face embeddings, and I would like to try out your code to cluster them as good as possible (dsgcn), but I am encoutering errors. Could you help me out?
I don't know what exactly I need to do. I have followed all the steps, and I have a data directory structure like this:

```
data
  ├── features
    ├── features.bin
  ├── pretrained_models
    ├── pretrained_gcn_d_ms1m.pth
    ├── pretrained_gcn_s_ms1m.pth 
    ├── pretrained_gcn_d_iop_ms1m.pth
```

This is the output I get:

```
/content/nv/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
meta file not found: ./data/labels/part1_test.meta.
init `lb2idxs` and `idx2lb` as None.
Traceback (most recent call last):
  File "/content/drive/MyDrive/GitHub/learn-to_cluster/dsgcn/main.py", line 104, in <module>
    main()
  File "/content/drive/MyDrive/GitHub/learn-to_cluster/dsgcn/main.py", line 54, in main
    cfg = Config.fromfile(args.config)
  File "/content/nv/lib/python3.9/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/content/nv/lib/python3.9/site-packages/mmcv/utils/config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/tmpu9up9ydu/tmpy8wkfl35.py", line 76, in <module>
  File "/content/drive/MyDrive/GitHub/learn-to_cluster/proposals/generate_proposals.py", line 38, in generate_proposals
    ds = BasicDataset(name=name,
  File "/content/drive/MyDrive/GitHub/learn-to_cluster/utils/dataset.py", line 39, in __init__
    self.features = read_probs(self.feat_path,
  File "/content/drive/MyDrive/GitHub/learn-to_cluster/utils/misc.py", line 78, in read_probs
    probs = probs.reshape(inst_num, feat_dim)
ValueError: cannot reshape array of size 671140 into shape (256)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fd49ad46430>
Traceback (most recent call last):
  File "/usr/lib/python3.9/tempfile.py", line 584, in __del__
    self.close()
  File "/usr/lib/python3.9/tempfile.py", line 580, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpu9up9ydu/tmpy8wkfl35.py'
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-8-537639c52c55>](https://localhost:8080/#) in <module>
----> 1 get_ipython().run_cell_magic('shell', '', 'source ./nv/bin/activate\ncd drive/MyDrive/GitHub/learn-to_cluster\nsh scripts/dsgcn/test_cluster_det_ms1m.sh\n')

3 frames
[/usr/local/lib/python3.9/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

CalledProcessError: Command 'source ./nv/bin/activate
cd drive/MyDrive/GitHub/learn-to_cluster
sh scripts/dsgcn/test_cluster_det_ms1m.sh
' returned non-zero exit status 1.
```

**Comment by Ji2-yadav** [comment]
Let me know if anyone was able to resolve this.
