### ISSUE TITLE
error in file: sh scripts/test_cluster_det.sh

### ISSUE THREAD

**Issue by aa12356jm** [yl-1993/learn-to-cluster#16]
**run : sh scripts/test_cluster_det.sh,it  give errors as follows:**
`trainer@f7c6756f593f:/data/raid/learn-to-cluster$ sh scripts/test_cluster_det.sh
[2019-07-26 01:13:57,415] Set random seed to 42
[./data/labels/part1_test.meta] #cls: 8573, #inst: 584013
[Time] read meta and feature consumes 1.5541 s
read proposals from folder:  ./data/cluster_proposals/part1_test/faiss_k_80_th_0.7_step_0.05_minsz_3_maxsz_300_iter_0/proposals/
read proposals from folder:  ./data/cluster_proposals/part1_test/faiss_k_80_th_0.75_step_0.05_minsz_3_maxsz_300_iter_0/proposals/
[Time] read proposal list consumes 0.5840 s
#cluster: 34578, #output: 1, feature shape: (584013, 256), norm_adj: True, wo_weight: False
Traceback (most recent call last):
  File "dsgcn/main.py", line 80, in <module>
    main()
  File "dsgcn/main.py", line 76, in main
    handler(model, cfg, logger)
  File "/data/raid/learn-to-cluster/dsgcn/test_cluster_det.py", line 48, in test_cluster_det
    for i, data in enumerate(data_loader):
  File "/home/trainer/anaconda3/envs/pytorch_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/trainer/anaconda3/envs/pytorch_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/trainer/anaconda3/envs/pytorch_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/raid/learn-to-cluster/dsgcn/datasets/build_dataloader.py", line 39, in collate_graphs
    pad_feat = default_collate(pad_feat)
  File "/home/trainer/anaconda3/envs/pytorch_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 137, in default_collate
    raise TypeError((error_msg.format(type(batch[0]))))
TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'torch.autograd.variable.Variable'>`

**Comment by aa12356jm** [comment]
pytorch version  error, solved it
