### ISSUE TITLE
Issue on test gcn E fashion

### ISSUE THREAD

**Issue by yanbai1993** [yl-1993/learn-to-cluster#40]
When I test the gcn E on fashion dataset, I meet an issue: FileNotFoundError: [Errno 2] No such file or directory: './data/work_dir/cfg_test_gcnv_fashion/pred_confs.npz'.

The issue occurs when I use the model provided by the author. I have followed the instruction, first perform "sh scripts/vegcn/test_gcn_v_ms1m.sh" , then perform "sh scripts/vegcn/test_gcn_e_ms1m.sh".

More details:
[2020-04-28 09:18:43,381] Set random seed to 42
[./data/labels/deepfashion_test.meta] #cls: 3991, #inst: 26960
[Time] read meta and feature consumes 0.0498 s
feature shape: (26960, 512), k: 80, norm_feat: True
read knn from ./data/work_dir/cfg_test_gcnv_fashion/deepfashion_test_gcnv_k_5_th_0.0/knns/pretrained_gcn_v_fashion/faiss_k_80.npz
read estimated confidence from ./data/work_dir/cfg_test_gcnv_fashion/pred_confs.npz
[Time] read knn graph consumes 0.4678 s
Traceback (most recent call last):
  File "vegcn/main.py", line 104, in <module>
    main()
  File "vegcn/main.py", line 100, in main
    handler(model, cfg, logger)
  File "/home/by/workspace/DA/learn-to-cluster/vegcn/test_gcn_e.py", line 105, in test_gcn_e
    dataset = build_dataset(cfg.model['type'], cfg.test_data)
  File "/home/by/workspace/DA/learn-to-cluster/vegcn/datasets/__init__.py", line 13, in build_dataset
    return __factory__[model_type](cfg)
  File "/home/by/workspace/DA/learn-to-cluster/vegcn/datasets/gcn_e_dataset.py", line 77, in __init__
    self.confs = np.load(cfg.pred_confs)['pred_confs']
  File "/home/by/.conda/envs/torch1.0_python3.6/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/work_dir/cfg_test_gcnv_fashion/pred_confs.npz'

**Comment by yl-1993** [comment]
@yanbai1993 Have you performed `sh scripts/vegcn/test_gcn_v_fashion.sh` before `sh scripts/vegcn/test_gcn_e_fashion.sh`?
