### ISSUE TITLE
Issue on multi-gpus train

### ISSUE THREAD

**Issue by keeprunningcelin** [yl-1993/learn-to-cluster#43]
Hi Yang Lei,I try to add multi-gpus train,but get error when run the .sh file.

Traceback (most recent call last):
  File "vegcn/main.py", line 105, in <module>
    main()
  File "vegcn/main.py", line 101, in main
    handler(model, cfg, logger)
  File "/home/celin/learn-to-cluster/vegcn/train_gcn_v.py", line 37, in train_gcn_v
    _single_train(model, dataset, cfg)
  File "/home/celin/learn-to-cluster/vegcn/train_gcn_v.py", line 68, in _single_train
    runner.run(train_data, cfg.workflow, cfg.total_epochs)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/celin/learn-to-cluster/vegcn/runner/runner.py", line 17, in train_gcnv
    **kwargs)
  File "/home/celin/learn-to-cluster/vegcn/train_gcn_v.py", line 17, in batch_processor
    _, loss = model(data, return_loss=True)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 119, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 130, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 17, in scatter_map
    return list(map(list, zip(*map(scatter_map, obj))))
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 87, in forward
    outputs = comm.scatter(input, ctx.target_gpus, ctx.chunk_sizes, ctx.dim, streams)
  File "/home/celin/anaconda3/lib/python3.6/site-packages/torch/cuda/comm.py", line 142, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: sparse tensors do not have strides (strides at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/ATen/SparseTensorImpl.cpp:39)
frame #0: at::native::slice(at::Tensor const&, long, long, long, long) + 0x97 (0x7f17009baa77 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #1: at::Type::slice(at::Tensor const&, long, long, long, long) const + 0x4e (0x7f1700b6914e in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #2: at::native::narrow(at::Tensor const&, long, long, long) + 0xb1 (0x7f17009bd481 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #3: at::Type::narrow(at::Tensor const&, long, long, long) const + 0x49 (0x7f1700b6a639 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #4: at::native::split(at::Tensor const&, long, long) + 0x1a7 (0x7f17009bf857 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #5: at::Type::split(at::Tensor const&, long, long) const + 0x41 (0x7f1700b68fd1 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #6: torch::autograd::VariableType::split(at::Tensor const&, long, long) const + 0x3ce (0x7f16e3a894de in /home/celin/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #7: at::native::chunk(at::Tensor const&, long, long) + 0x80 (0x7f17009bebe0 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #8: at::Type::chunk(at::Tensor const&, long, long) const + 0x41 (0x7f1700b6e9e1 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #9: torch::autograd::VariableType::chunk(at::Tensor const&, long, long) const + 0x183 (0x7f16e3a75de3 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #10: torch::cuda::scatter(at::Tensor const&, at::ArrayRef<long>, at::optional<std::vector<long, std::allocator<long> > > const&, long, at::optional<std::vector<CUDAStreamInternals*, std::allocator<CUDAStreamInternals*> > > const&) + 0xd98 (0x7f16e3e76128 in /home/celin/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0xc42a0b (0x7f16e3e7da0b in /home/celin/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x38a5cb (0x7f16e35c55cb in /home/celin/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #23: THPFunction_apply(_object*, _object*) + 0x38f (0x7f16e39a3a2f in /home/celin/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)

I'd like to know how to train with multi-gpus.
Thanks.

**Comment by yl-1993** [comment]
@keeprunningcelin Sorry for the late reply.
(1) To train GCN-V with multiple gpus, a simple solution is to first randomly sample sub-graphs from the entire graph and apply [DataParallel](https://github.com/rusty1s/pytorch_geometric/blob/281c32518464a3ff870e61229ba9d28206867ed8/torch_geometric/nn/data_parallel.py#L8) strategy. But it will not perform the exact computation as the current method, which trains on the entire graph in each iteration.
(2) To train GCN-E with multiple gpus, DataParallel strategy can be directly applied as it is based on selected sub-graphs.
