### ISSUE TITLE
Issue on test gcn E fashion

### ISSUE THREAD

**Issue by voidart-dwang** [yl-1993/learn-to-cluster#68]
When I test the gcn E on fashion dataset, I meet an issue.

Traceback (most recent call last):
  File "vegcn/main.py", line 105, in <module>
    main()
  File "vegcn/main.py", line 48, in main
    cfg = Config.fromfile(args.config)
  File "/home/zdk/anaconda3/envs/wda/lib/python3.6/site-packages/mmcv/utils/config.py", line 152, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/home/zdk/anaconda3/envs/wda/lib/python3.6/site-packages/mmcv/utils/config.py", line 91, in _file2dict
    mod = import_module('_tempconfig')
  File "/home/zdk/anaconda3/envs/wda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/tmp/tmps4lsacyp/_tempconfig.py", line 25, in <module>
  File "/home/zdk/anaconda3/envs/wda/lib/python3.6/site-packages/mmcv/utils/config.py", line 202, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/zdk/anaconda3/envs/wda/lib/python3.6/site-packages/mmcv/utils/config.py", line 34, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'model'

**Comment by yl-1993** [comment]
@voidart-dwang It seems that this issue is aroused by mmcv version. Please refer to a similar issue and discussion https://github.com/yl-1993/learn-to-cluster/issues/36 .
